version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  theemmerdor:
    image: docker.pkg.github.com/clabroche/docker-registry/theemmerdor:latest
    hostname: theemmerdor
    restart: always
    volumes:
      - ./urlToTests.json:/theemmerdor/src/urlToTests.json
    environment:
      URLS: http://some-site.com,https://another-site/somewhere
      DISCORD_TOKEN: <your token from your discord bot>
      CHANNEL_ID: <your discord channel to send msg>
    labels:
      com.centurylinklabs.watchtower.enable: "true"
